### ISSUE TITLE
Quest 3 controller position is wrong

### ISSUE THREAD

**Issue by joebobbio** [Meumeu/WiVRn#106] opened 2024-08-14 01:03 UTC
Hello,
I've recently noticed that the actual controller position in my hand does not match the displayed model in the waiting room.
This also applies to games, where my controller offsets are also incorrect (hand is a fair bit lower than it should be). This issue isn't present in native Oculus games, and hand tracking seems to be unaffected.
![org meumeu wivrn-20240813-205415](https://github.com/user-attachments/assets/55a81928-c2a5-420b-b1db-1e2339312829)

**Comment by xytovl** [comment] 2024-08-14 08:03
Seems to be a duplicate of #94

**Closed by xytovl** 2024-08-14 08:03 UTC
