### ISSUE TITLE
fails to initalize video codec even when running on dgpu

### ISSUE THREAD

**Issue by space2ninja101** [Meumeu/WiVRn#76] opened 2024-06-12 02:03 UTC
```
~$ prime-run wivrn-server
WiVRn c92bcd7 starting
Service published: artix
Cannot set active OpenXR runtime: filesystem error: cannot create symlink: File exists [/usr/share/openxr/1/openxr_wivrn.json] [/home/space/.config/openxr/1/active_runtime.json]
Server started, PID 6718
 INFO [ipc_server_main]  'v21.0.0-4402-gffb71af2' starting up...
DEBUG [comp_main_create_system_compositor] Doing init 0x5b12b5770d90
Can't open bumblebee display.
 WARN [build_device_extensions] Duplicate device extension VK_KHR_external_memory_fd not added twice
 WARN [build_device_extensions] Duplicate device extension VK_KHR_external_memory_fd not added twice
 WARN [build_device_extensions] Duplicate device extension VK_KHR_external_memory_fd not added twice
 INFO [create_device] Created device and COMPUTE queue with QUEUE_GLOBAL_PRIORITY_MEDIUM.
 INFO [vk_print_device_info] Device info:
	name: NVIDIA GeForce GTX 970M
	vendor: 0x10de
	product: 0x13d8
	deviceType: VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
	apiVersion: 1.3.277
	driverVersion: 0x89938000
 INFO [vk_print_features_info] Features:
	timestamp_compute_and_graphics: true
	timestamp_period: 1.000000
	timestamp_valid_bits: 64
	timeline_semaphore: true
 INFO [vk_print_external_handles_info] Supported images:
	VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT:
		color import=true export=true
		depth import=true export=true
 INFO [vk_print_external_handles_info] Supported fences:
	VK_EXTERNAL_FENCE_HANDLE_TYPE_SYNC_FD_BIT: true
	VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_FD_BIT: true
 INFO [vk_print_external_handles_info] Supported semaphores:
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT(binary): true
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT(binary): true
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT(timeline): false
	VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT(timeline): true
15 HEVC presets
  Preset {b2dfb705-4ebd-4c49-9b5f-24a777d3e587}
  Preset {49df21c5-6dfa-4feb-9787-6acc9effb726}
  Preset {60e4c59f-e846-4484-a56d-cd45be9fddf6}
  Preset {34dba71d-a77b-4b8f-9c3e-b6d5da24c012}
  Preset {82e3e450-bdbb-4e40-989c-82a90df9ef32}
  Preset {c5f733b9-ea97-4cf9-bec2-bf78a74fd105}
  Preset {67082a44-4bad-48fa-98ea-93056d150a58}
  Preset {7add423d-d035-4f6f-aea5-50885658643c}
  Preset {fc0a8d3e-45f8-4cf8-80c7-298871590ebf}
  Preset {f581cfb8-88d6-4381-93f0-df13f9c27dab}
  Preset {36850110-3a07-441f-94d5-3670631f91f6}
  Preset {90a7b826-df06-4862-b9d2-cd6d73a08681}
  Preset {21c6e6b4-297a-4cba-998f-b6cbde72ade3}
  Preset {8e75c279-6299-4ab6-8302-0b215a335cf5}
  Preset {84848c12-6f71-4c13-931b-53e283f57974}
ERROR [VideoEncoderNvenc] /home/space/.cache/yay/wivrn-server/src/WiVRn-0.15/server/encoder/video_encoder_nvenc.cpp:279: 8, 
ERROR [comp_wivrn_create_images] Failed to create video encoder: TODO
Server exited, exit status 0, received signal ABRT (Aborted)
Service published: artix

```

**Comment by xytovl** [comment] 2024-06-12 07:05
Seems to be a duplicate of https://github.com/Meumeu/WiVRn/issues/70
Can you validate the fix in branch https://github.com/Meumeu/WiVRn/tree/fix/nvenc-color-scale then report the result on issue 70?

**Closed by xytovl** 2024-06-12 07:05 UTC
